/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SeriesAAnnouncementRouteImport } from './routes/series-a-announcement'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductRouteImport } from './routes/product'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppWorkflowsRouteImport } from './routes/_authenticated/app.workflows'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/app.settings'
import { Route as AuthenticatedAppRunsRouteImport } from './routes/_authenticated/app.runs'
import { Route as AuthenticatedAppIntegrationsRouteImport } from './routes/_authenticated/app.integrations'
import { Route as AuthenticatedAppDocumentsRouteImport } from './routes/_authenticated/app.documents'
import { Route as AuthenticatedAppApiRouteImport } from './routes/_authenticated/app.api'
import { Route as AuthenticatedAppWorkflowsIdRouteImport } from './routes/_authenticated/app.workflows_.$id'

const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesAAnnouncementRoute = SeriesAAnnouncementRouteImport.update({
  id: '/series-a-announcement',
  path: '/series-a-announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkflowsRoute =
  AuthenticatedAppWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRunsRoute = AuthenticatedAppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppIntegrationsRoute =
  AuthenticatedAppIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsRoute =
  AuthenticatedAppDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppApiRoute = AuthenticatedAppApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkflowsIdRoute =
  AuthenticatedAppWorkflowsIdRouteImport.update({
    id: '/workflows_/$id',
    path: '/workflows/$id',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/series-a-announcement': typeof SeriesAAnnouncementRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/app/api': typeof AuthenticatedAppApiRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/runs': typeof AuthenticatedAppRunsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/workflows/$id': typeof AuthenticatedAppWorkflowsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/series-a-announcement': typeof SeriesAAnnouncementRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/app/api': typeof AuthenticatedAppApiRoute
  '/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/app/runs': typeof AuthenticatedAppRunsRoute
  '/app/settings': typeof AuthenticatedAppSettingsRoute
  '/app/team': typeof AuthenticatedAppTeamRoute
  '/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/workflows/$id': typeof AuthenticatedAppWorkflowsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customers': typeof CustomersRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/reset-password': typeof ResetPasswordRoute
  '/series-a-announcement': typeof SeriesAAnnouncementRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/industries/$slug': typeof IndustriesSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/_authenticated/app/api': typeof AuthenticatedAppApiRoute
  '/_authenticated/app/documents': typeof AuthenticatedAppDocumentsRoute
  '/_authenticated/app/integrations': typeof AuthenticatedAppIntegrationsRoute
  '/_authenticated/app/runs': typeof AuthenticatedAppRunsRoute
  '/_authenticated/app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRoute
  '/_authenticated/app/workflows': typeof AuthenticatedAppWorkflowsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/workflows_/$id': typeof AuthenticatedAppWorkflowsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/login'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/series-a-announcement'
    | '/signup'
    | '/solutions'
    | '/app'
    | '/industries/$slug'
    | '/industries/'
    | '/app/api'
    | '/app/documents'
    | '/app/integrations'
    | '/app/runs'
    | '/app/settings'
    | '/app/team'
    | '/app/workflows'
    | '/app/'
    | '/app/workflows/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/customers'
    | '/login'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/series-a-announcement'
    | '/signup'
    | '/solutions'
    | '/industries/$slug'
    | '/industries'
    | '/app/api'
    | '/app/documents'
    | '/app/integrations'
    | '/app/runs'
    | '/app/settings'
    | '/app/team'
    | '/app/workflows'
    | '/app'
    | '/app/workflows/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/customers'
    | '/login'
    | '/pricing'
    | '/product'
    | '/reset-password'
    | '/series-a-announcement'
    | '/signup'
    | '/solutions'
    | '/_authenticated/app'
    | '/industries/$slug'
    | '/industries/'
    | '/_authenticated/app/api'
    | '/_authenticated/app/documents'
    | '/_authenticated/app/integrations'
    | '/_authenticated/app/runs'
    | '/_authenticated/app/settings'
    | '/_authenticated/app/team'
    | '/_authenticated/app/workflows'
    | '/_authenticated/app/'
    | '/_authenticated/app/workflows_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomersRoute: typeof CustomersRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SeriesAAnnouncementRoute: typeof SeriesAAnnouncementRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series-a-announcement': {
      id: '/series-a-announcement'
      path: '/series-a-announcement'
      fullPath: '/series-a-announcement'
      preLoaderRoute: typeof SeriesAAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workflows': {
      id: '/_authenticated/app/workflows'
      path: '/workflows'
      fullPath: '/app/workflows'
      preLoaderRoute: typeof AuthenticatedAppWorkflowsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/settings': {
      id: '/_authenticated/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/runs': {
      id: '/_authenticated/app/runs'
      path: '/runs'
      fullPath: '/app/runs'
      preLoaderRoute: typeof AuthenticatedAppRunsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/integrations': {
      id: '/_authenticated/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AuthenticatedAppIntegrationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/documents': {
      id: '/_authenticated/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AuthenticatedAppDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/api': {
      id: '/_authenticated/app/api'
      path: '/api'
      fullPath: '/app/api'
      preLoaderRoute: typeof AuthenticatedAppApiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workflows_/$id': {
      id: '/_authenticated/app/workflows_/$id'
      path: '/workflows/$id'
      fullPath: '/app/workflows/$id'
      preLoaderRoute: typeof AuthenticatedAppWorkflowsIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppApiRoute: typeof AuthenticatedAppApiRoute
  AuthenticatedAppDocumentsRoute: typeof AuthenticatedAppDocumentsRoute
  AuthenticatedAppIntegrationsRoute: typeof AuthenticatedAppIntegrationsRoute
  AuthenticatedAppRunsRoute: typeof AuthenticatedAppRunsRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRoute
  AuthenticatedAppWorkflowsRoute: typeof AuthenticatedAppWorkflowsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppWorkflowsIdRoute: typeof AuthenticatedAppWorkflowsIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppApiRoute: AuthenticatedAppApiRoute,
  AuthenticatedAppDocumentsRoute: AuthenticatedAppDocumentsRoute,
  AuthenticatedAppIntegrationsRoute: AuthenticatedAppIntegrationsRoute,
  AuthenticatedAppRunsRoute: AuthenticatedAppRunsRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRoute,
  AuthenticatedAppWorkflowsRoute: AuthenticatedAppWorkflowsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppWorkflowsIdRoute: AuthenticatedAppWorkflowsIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomersRoute: CustomersRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SeriesAAnnouncementRoute: SeriesAAnnouncementRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
